#!/usr/bin/env bash
# Generates web/.env.local from root .env
# Maps root environment variables to NEXT_PUBLIC_* equivalents for the web frontend
#
# Usage:
#   ./scripts/generate-web-env.sh
#
# This script reads the root .env file and generates web/.env.local with proper
# NEXT_PUBLIC_* prefixed variables. The root .env is the single source of truth
# for all environment configuration.
#
# NOTE: SKIP_ADDRESS_EQUALITY_CHECK is NOT propagated by this script.
# If AcUSDY and CollateralLocker have the same address (same nonce deployment),
# set SKIP_ADDRESS_EQUALITY_CHECK=true directly in shell or web/.env.local.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"
WEB_ENV_FILE="$ROOT_DIR/web/.env.local"

# Variables to map from root .env to web/.env.local
# Format: "ROOT_VAR_NAME" -> "NEXT_PUBLIC_ROOT_VAR_NAME"
MAPPED_VARS=(
    # Network RPC endpoints
    "MANTLE_RPC_VTE"
    "ETHEREUM_RPC_VTE"
    "MANTLE_RPC"
    "ETHEREUM_RPC"

    # Deployed contract addresses
    "MANTLE_LOCKER"
    "ETH_ACUSDY"
    "ETH_ORACLE"
    "ETH_ADAPTER"

    # Real mainnet contract addresses
    "ETH_MORPHO"
    "ETH_USDC"
    "ETH_IRM"
    "MANTLE_USDY"

    # Web-specific configuration
    "DYNAMIC_ENVIRONMENT_ID"
    "USE_MAINNET"
    "MORPHO_MARKET_ID"
    "MARKET_LLTV"
    "MANTLE_VTE_EXPLORER"
    "ETHEREUM_VTE_EXPLORER"
)

# Check if root .env exists
if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: Root .env file not found at $ENV_FILE"
    echo "Please create the root .env file first."
    exit 1
fi

echo "Generating web/.env.local from root .env..."
echo ""

# Create web directory if it doesn't exist
mkdir -p "$(dirname "$WEB_ENV_FILE")"

# Start with header comment
cat > "$WEB_ENV_FILE" << 'EOF'
# Auto-generated by scripts/generate-web-env.sh
# DO NOT EDIT DIRECTLY - modify root .env and regenerate
#
# To regenerate: ./scripts/generate-web-env.sh
#
# See root .env.example for documentation of each variable

EOF

# Source the root .env to get variable values
set +u  # Allow unset variables during sourcing
# shellcheck disable=SC1090
source "$ENV_FILE"
set -u

# Track which variables were found
FOUND_COUNT=0
MISSING_VARS=()

# Process each mapped variable
for var in "${MAPPED_VARS[@]}"; do
    # Get the value from environment (set by sourcing .env)
    value="${!var:-}"

    if [[ -n "$value" ]]; then
        # Write to web/.env.local with NEXT_PUBLIC_ prefix
        echo "NEXT_PUBLIC_${var}=${value}" >> "$WEB_ENV_FILE"
        FOUND_COUNT=$((FOUND_COUNT + 1))
        echo "  + NEXT_PUBLIC_${var}"
    else
        MISSING_VARS+=("$var")
    fi
done

echo ""
echo "Generated $FOUND_COUNT variables to $WEB_ENV_FILE"

# Report missing variables (warnings, not errors - some may be optional)
if [[ ${#MISSING_VARS[@]} -gt 0 ]]; then
    echo ""
    echo "Missing from root .env (may be optional):"
    for var in "${MISSING_VARS[@]}"; do
        echo "  - $var"
    done
fi

echo ""
echo "Done! Web frontend can now be started with: cd web && npm run dev"
